name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    # Los runners cuentan con software preinstalado como NodeJS
    steps: 
      - name: Get code
    #   para usar actiones se utiliza la keyword uses
        uses: actions/checkout@v3
        # para configurar los parámetrode de la action se usa "with" y depende de c/action
        # si no se tuviera NodeJS instalado se podría instalar con actions/setup-node@v3:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
