name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs: 
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/setup-node@v3
      with:
        node-version: 18
      run: npm ci
      shell: bash