name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
        # Se pueden ejecutar en paralelo con dos versiones del SO, node v, ... todas las combinaciones posibles
      matrix:
        node-version: [16, 17, 18]
        operating-system: [ubuntu-latest, windows-latest]
        # Si se requiere una combinación especial, se puede añadir con include
        include: 
            - node-version: 15
            - operating-system: ubuntu-latest
        # También excluir
        exclude:
            - node-version: 17
            - operating-system: windows-latest

    runs-on: ${{ matrix.operating-system }}
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build