name: First Workflow
# on: para definir cuándo se ejecutará
# workflow_dispatch:  hace que el desencadenante sea manual
on: workflow_dispatch
jobs:
  first_job:
  # runs-on: definición del environment
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"